name: Build Apps

on:
  push:
    paths:
      - "apps/**"
env:
  AZURE_CONTAINER_REGISTRY_NAME: acrab
  APP_NAME: template-api
  APP_PORT: 8080

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS }}
          auth-type: SERVICE_PRINCIPAL

      - name: Build API
        uses: azure/CLI@v1
        with:
          azcliversion: 2.55.0
          inlineScript: |
            az acr build --registry $AZURE_CONTAINER_REGISTRY_NAME --image ${{env.APP_NAME}}:$GITHUB_SHA --file apps/src/Template.Api/Dockerfile apps

      - name: Build Jobs
        uses: azure/CLI@v1
        with:
          azcliversion: 2.55.0
          inlineScript: |
            az acr build --registry $AZURE_CONTAINER_REGISTRY_NAME --image template-jobs:$GITHUB_SHA --file apps/src/Template.Jobs/Dockerfile apps

  deploy_staging:
    name: deploy_staging
    runs-on: ubuntu-22.04
    environment: staging
    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS }}
          auth-type: SERVICE_PRINCIPAL

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.55.0
          inlineScript: |
            set -x
            chmod +x ./apps/scripts/deploy-apps.sh
            chmod +x ./apps/scripts/deploy-jobs.sh
            wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.41.1/yq_linux_amd64
            chmod +x /usr/local/bin/yq

            ./apps/scripts/deploy-apps.sh staging $GITHUB_SHA rg-trading
            ./apps/scripts/deploy-jobs.sh staging $GITHUB_SHA rg-trading

    needs: [build]
