name: Deploy Platform

on: push
jobs:
  publish:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS }}
          auth-type: SERVICE_PRINCIPAL

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.55.0
          inlineScript: |
            az deployment sub create \
              --name first \
              --template-file infra/main.bicep \
              --parameters environment=staging \
              --location australiaeast
